services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: video-game-database
    environment:
      MSSQL_SA_PASSWORD: "NewtonAssignment@2025" #Ideally make this a secret
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume: